
-- Base de données: `ENTSOO`
--
DROP DATABASE IF EXISTS `CLIENTSOO`;

CREATE DATABASE IF NOT EXISTS `CLIENTSOO` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;
USE `CLIENTSOO`;

-- --------------------------------------------------------

--
-- Structure de la table `cours`
--


DROP TABLE IF EXISTS CLIENT CASCADE ;
DROP TABLE IF EXISTS PRODUIT CASCADE ;
DROP TABLE IF EXISTS COMMANDE CASCADE ;
DROP TABLE IF EXISTS LIGNE_COMMANDE CASCADE ;



  CREATE TABLE IF NOT EXISTS CLIENT 
   (`id` INTEGER NOT NULL AUTO_INCREMENT, 
	`titre` VARCHAR(12)  NOT NULL DEFAULT 'Monsieur', 
	`nom` VARCHAR(30) NOT NULL , 
	`prenom` VARCHAR(30) NOT NULL , 
	`adresserue1` VARCHAR(40) NOT NULL , 
	`adresserue2` VARCHAR(40), 
	`cp` VARCHAR(6) NOT NULL , 
	`ville` VARCHAR(30) NOT NULL , 
	`tel` VARCHAR(14) NOT NULL ,
	CONSTRAINT PK_ENT PRIMARY KEY (ID)
   ) ;
  
  ALTER TABLE CLIENT ADD CONSTRAINT CKC_TITRE_ENT CHECK (TITRE in ('Monsieur','Madame','Mademoiselle')) ;

--
--  DDL for Table PRODUIT
--

  CREATE TABLE IF NOT EXISTS PRODUIT 
   (ID INTEGER NOT NULL AUTO_INCREMENT, 
	DESIGNATION VARCHAR(50), 
	PUHT DECIMAL(7,2),
	CONSTRAINT PK_PRODUIT PRIMARY KEY (ID)
   ) ;
     
--
--  DDL for Table COMMANDE
--

  CREATE TABLE IF NOT EXISTS COMMANDE 
   (`id` INTEGER NOT NULL AUTO_INCREMENT, 
	`idclient` INTEGER  NOT NULL , 
	`datecde` DATE  NOT NULL,
	CONSTRAINT PK_COMMANDE PRIMARY KEY (`id`)
   ) ;
   
   ALTER TABLE COMMANDE ADD CONSTRAINT FK_COMMANDE_CLIENT FOREIGN KEY (`idclient`)
	  REFERENCES CLIENT (`id`) ;
--
--  DDL for Table LIGNE_COMMANDE
--
  CREATE TABLE IF NOT EXISTS LIGNE_COMMANDE 
   (IDCOMMANDE INTEGER  NOT NULL , 
	IDPRODUIT INTEGER, 
	QTELIGNE INTEGER  NOT NULL 
   ) ;
   ALTER TABLE LIGNE_COMMANDE ADD CONSTRAINT PK_LIGNE_COMMANDE PRIMARY KEY (IDCOMMANDE, IDPRODUIT) ;
   ALTER TABLE LIGNE_COMMANDE ADD CONSTRAINT FK_LIGNE_COMMANDE FOREIGN KEY (IDCOMMANDE)
	  REFERENCES COMMANDE (ID) ;
   ALTER TABLE LIGNE_COMMANDE ADD CONSTRAINT FK_LIGNE_PRODUIT FOREIGN KEY (IDPRODUIT)
	  REFERENCES PRODUIT (ID) ;


   
Insert into CLIENT (TITRE,NOM,PRENOM,ADRESSERUE1,ADRESSERUE2,CP,VILLE,TEL) values ('Monsieur','Tienun','Jean','112, rue du Départ',null,'13000 ','Marseille','0404040404');
Insert into CLIENT (TITRE,NOM,PRENOM,ADRESSERUE1,ADRESSERUE2,CP,VILLE,TEL) values ('Madame','Terrature','Julie','Résidence Mermoz','1234 Boulevard des Aviateurs','14000 ','Caen','0202020202');
Insert into CLIENT (TITRE,NOM,PRENOM,ADRESSERUE1,ADRESSERUE2,CP,VILLE,TEL) values ('Mademoiselle','Morizet','Patricia','Hameau de Pau','23 Boulevard du Lycée','33000 ','Bordeaux','0250505052');
Insert into CLIENT (TITRE,NOM,PRENOM,ADRESSERUE1,ADRESSERUE2,CP,VILLE,TEL) values ('Monsieur','Nolapin','Jean','12 quai des Brumes',null,'83000 ','Toulon','0404505050');
Insert into CLIENT (TITRE,NOM,PRENOM,ADRESSERUE1,ADRESSERUE2,CP,VILLE,TEL) values ('Monsieur','Entete','Martel','Résidence du Faron','30 rue du téléphérique','83000 ','Toulon','0250505050');
Insert into CLIENT (TITRE,NOM,PRENOM,ADRESSERUE1,ADRESSERUE2,CP,VILLE,TEL) values ('Monsieur','Entete','Martel','12 Avenue de Lille',null, '59140 ','Dunkerque','0250905057');
Insert into CLIENT (TITRE,NOM,PRENOM,ADRESSERUE1,ADRESSERUE2,CP,VILLE,TEL) values ('Madame','DUMANS','Henriette','Corniche des Bolides','Villa Ferrari', '49000 ','Angers','0250765357');
Insert into CLIENT (TITRE,NOM,PRENOM,ADRESSERUE1,ADRESSERUE2,CP,VILLE,TEL) values ('Madame','Cerf','Paulette','343 Avenue Henri Barbusse',null,'33000 ','Bordeaux','0550505050');


Insert into PRODUIT (DESIGNATION,PUHT) values ('CARS 2 - MARTIN - Voiture radiocommandée 1/16ème',29.99);
Insert into PRODUIT (DESIGNATION,PUHT) values ('Lego Super Héros - La poursuite De Catwoman',11.19);
Insert into PRODUIT (DESIGNATION,PUHT) values ('Titeuf, L''Ecole En Folie',5.49);
Insert into PRODUIT (DESIGNATION,PUHT) values ('Robot Tankbot Compatible Smartphone',13.99);
Insert into PRODUIT (DESIGNATION,PUHT) values ('Vélo VTT homme',67.99);
Insert into PRODUIT (DESIGNATION,PUHT) values ('Vélo VTT femme',59.99);
Insert into PRODUIT (DESIGNATION,PUHT) values ('Train électrique',45.99);
Insert into PRODUIT (DESIGNATION,PUHT) values ('Pompe Vélo',18.85);

Insert into COMMANDE (IDCLIENT,DATECDE) values (1,'2014-09-07');
Insert into COMMANDE (IDCLIENT,DATECDE) values (2,'2014-09-08');
Insert into COMMANDE (IDCLIENT,DATECDE) values (3,'2014-09-10');
Insert into COMMANDE (IDCLIENT,DATECDE) values (2,'2014-10-01');
Insert into COMMANDE (IDCLIENT,DATECDE) values (3,'2014-10-01');
Insert into COMMANDE (IDCLIENT,DATECDE) values (4,'2014-10-01');
Insert into COMMANDE (IDCLIENT,DATECDE) values (5,'2014-10-01');





Insert into LIGNE_COMMANDE (IDCOMMANDE,IDPRODUIT,QTELIGNE) values (1,1,2);
Insert into LIGNE_COMMANDE (IDCOMMANDE,IDPRODUIT,QTELIGNE) values (1,4,1);

Insert into LIGNE_COMMANDE (IDCOMMANDE,IDPRODUIT,QTELIGNE) values (2,1,3);
Insert into LIGNE_COMMANDE (IDCOMMANDE,IDPRODUIT,QTELIGNE) values (2,2,2);
Insert into LIGNE_COMMANDE (IDCOMMANDE,IDPRODUIT,QTELIGNE) values (2,3,4);

Insert into LIGNE_COMMANDE (IDCOMMANDE,IDPRODUIT,QTELIGNE) values (3,1,4);
Insert into LIGNE_COMMANDE (IDCOMMANDE,IDPRODUIT,QTELIGNE) values (3,2,2);
Insert into LIGNE_COMMANDE (IDCOMMANDE,IDPRODUIT,QTELIGNE) values (3,3,5);
Insert into LIGNE_COMMANDE (IDCOMMANDE,IDPRODUIT,QTELIGNE) values (3,4,3);
Insert into LIGNE_COMMANDE (IDCOMMANDE,IDPRODUIT,QTELIGNE) values (3,5,12);
Insert into LIGNE_COMMANDE (IDCOMMANDE,IDPRODUIT,QTELIGNE) values (3,7,5);
Insert into LIGNE_COMMANDE (IDCOMMANDE,IDPRODUIT,QTELIGNE) values (3,8,9);
Insert into LIGNE_COMMANDE (IDCOMMANDE,IDPRODUIT,QTELIGNE) values (3,6,7);

Insert into LIGNE_COMMANDE (IDCOMMANDE,IDPRODUIT,QTELIGNE) values (4,3,6);
Insert into LIGNE_COMMANDE (IDCOMMANDE,IDPRODUIT,QTELIGNE) values (4,4,6);

Insert into LIGNE_COMMANDE (IDCOMMANDE,IDPRODUIT,QTELIGNE) values (5,1,6);
Insert into LIGNE_COMMANDE (IDCOMMANDE,IDPRODUIT,QTELIGNE) values (5,2,2);
Insert into LIGNE_COMMANDE (IDCOMMANDE,IDPRODUIT,QTELIGNE) values (5,3,5);
Insert into LIGNE_COMMANDE (IDCOMMANDE,IDPRODUIT,QTELIGNE) values (5,4,3);
Insert into LIGNE_COMMANDE (IDCOMMANDE,IDPRODUIT,QTELIGNE) values (5,5,13);
Insert into LIGNE_COMMANDE (IDCOMMANDE,IDPRODUIT,QTELIGNE) values (5,7,5);
Insert into LIGNE_COMMANDE (IDCOMMANDE,IDPRODUIT,QTELIGNE) values (5,8,9);
Insert into LIGNE_COMMANDE (IDCOMMANDE,IDPRODUIT,QTELIGNE) values (5,6,7);

Insert into LIGNE_COMMANDE (IDCOMMANDE,IDPRODUIT,QTELIGNE) values (6,4,5);
Insert into LIGNE_COMMANDE (IDCOMMANDE,IDPRODUIT,QTELIGNE) values (6,5,12);

Insert into LIGNE_COMMANDE (IDCOMMANDE,IDPRODUIT,QTELIGNE) values (7,7,3);
Insert into LIGNE_COMMANDE (IDCOMMANDE,IDPRODUIT,QTELIGNE) values (7,5,9);

commit;